--
-- PostgreSQL database dump
--

\restrict OTJ4eKZoN1j7yLI9hcuxWqTCnCvNaFsBtDJphLhfXR9e9X0Zi6j3p01rDHBf5nT

-- Dumped from database version 17.9 (Debian 17.9-1.pgdg13+1)
-- Dumped by pg_dump version 17.9 (Debian 17.9-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: DeviceRegistartionModelEntities; Type: TABLE; Schema: public; Owner: HSquadAdmin
--

CREATE TABLE public."DeviceRegistartionModelEntities" (
    "Id" uuid NOT NULL,
    "DeviceToken" character varying(500) NOT NULL,
    "DevicePlatform" text NOT NULL,
    "UserId" integer,
    "CreatedAt" timestamp without time zone,
    "LastActiveAt" timestamp without time zone,
    "IsActive" boolean NOT NULL,
    "InstallationId" text NOT NULL
);


ALTER TABLE public."DeviceRegistartionModelEntities" OWNER TO "HSquadAdmin";

--
-- Name: Equipments; Type: TABLE; Schema: public; Owner: HSquadAdmin
--

CREATE TABLE public."Equipments" (
    "Id" integer NOT NULL,
    "MainWeapon" boolean NOT NULL,
    "NameMainWeapon" character varying(50),
    "SecondaryWeapon" boolean NOT NULL,
    "NameSecondaryWeapon" text,
    "HeadEquipment" boolean NOT NULL,
    "BodyEquipment" boolean NOT NULL,
    "UnloudingEquipment" boolean NOT NULL,
    "OwnerEquipmentId" integer NOT NULL
);


ALTER TABLE public."Equipments" OWNER TO "HSquadAdmin";

--
-- Name: Equipments_Id_seq; Type: SEQUENCE; Schema: public; Owner: HSquadAdmin
--

ALTER TABLE public."Equipments" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Equipments_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Events; Type: TABLE; Schema: public; Owner: HSquadAdmin
--

CREATE TABLE public."Events" (
    "Id" integer NOT NULL,
    "NameTeamEnemy" text,
    "NamePolygon" text NOT NULL,
    "Coordinates" text NOT NULL,
    "Date" date NOT NULL,
    "Time" time without time zone NOT NULL,
    "CountMembers" integer NOT NULL,
    "TeamId" integer NOT NULL
);


ALTER TABLE public."Events" OWNER TO "HSquadAdmin";

--
-- Name: EventsForAllCommands; Type: TABLE; Schema: public; Owner: HSquadAdmin
--

CREATE TABLE public."EventsForAllCommands" (
    "Id" integer NOT NULL,
    "NameGame" text NOT NULL,
    "TeamNameOrganization" text NOT NULL,
    "TeamIdOrganization" integer NOT NULL,
    "DescriptionShort" text NOT NULL,
    "DescriptionFull" text,
    "CoordinatesPolygon" text NOT NULL,
    "PolygonName" text,
    "DateAndTimeGame" timestamp without time zone NOT NULL
);


ALTER TABLE public."EventsForAllCommands" OWNER TO "HSquadAdmin";

--
-- Name: EventsForAllCommands_Id_seq; Type: SEQUENCE; Schema: public; Owner: HSquadAdmin
--

ALTER TABLE public."EventsForAllCommands" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."EventsForAllCommands_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Events_Id_seq; Type: SEQUENCE; Schema: public; Owner: HSquadAdmin
--

ALTER TABLE public."Events" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Events_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: HistoryEvents; Type: TABLE; Schema: public; Owner: HSquadAdmin
--

CREATE TABLE public."HistoryEvents" (
    "Id" integer NOT NULL,
    "NamePolygon" text NOT NULL,
    "CoordinatesPolygon" text NOT NULL,
    "DateEvent" date NOT NULL
);


ALTER TABLE public."HistoryEvents" OWNER TO "HSquadAdmin";

--
-- Name: HistoryEvents_Id_seq; Type: SEQUENCE; Schema: public; Owner: HSquadAdmin
--

ALTER TABLE public."HistoryEvents" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."HistoryEvents_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Notifications; Type: TABLE; Schema: public; Owner: HSquadAdmin
--

CREATE TABLE public."Notifications" (
    "Id" integer NOT NULL,
    "Title" text NOT NULL,
    "Message" text NOT NULL,
    "Type" integer NOT NULL,
    "Priority" integer NOT NULL,
    "RelatedUserId" integer,
    "DataJson" text NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "IsRead" boolean NOT NULL,
    "IsSent" boolean NOT NULL,
    "UserId" integer,
    "EventId" integer
);


ALTER TABLE public."Notifications" OWNER TO "HSquadAdmin";

--
-- Name: Notifications_Id_seq; Type: SEQUENCE; Schema: public; Owner: HSquadAdmin
--

ALTER TABLE public."Notifications" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Notifications_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: PlayerStatistics; Type: TABLE; Schema: public; Owner: HSquadAdmin
--

CREATE TABLE public."PlayerStatistics" (
    "Id" integer NOT NULL,
    "NamePlayer" text NOT NULL,
    "CallSingPlayer" text NOT NULL,
    "CountKill" integer NOT NULL,
    "CountDieds" integer NOT NULL,
    "CountFees" integer NOT NULL,
    "CountEvents" integer NOT NULL,
    "LastUpdateDataStatistics" timestamp without time zone NOT NULL,
    "OldDataJson" text,
    "DataRegistr" timestamp without time zone,
    "RoleUser" smallint NOT NULL,
    "AchievementsJson" text,
    "IsCommanderCheck" boolean NOT NULL,
    "UserModelId" integer NOT NULL
);


ALTER TABLE public."PlayerStatistics" OWNER TO "HSquadAdmin";

--
-- Name: PlayerStatistics_Id_seq; Type: SEQUENCE; Schema: public; Owner: HSquadAdmin
--

ALTER TABLE public."PlayerStatistics" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PlayerStatistics_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Players; Type: TABLE; Schema: public; Owner: HSquadAdmin
--

CREATE TABLE public."Players" (
    "Id" integer NOT NULL,
    _role smallint NOT NULL,
    "_callSing" text NOT NULL,
    "_teamName" text NOT NULL,
    "_phoneNumber" text NOT NULL,
    "_userName" text,
    _age integer,
    "_isStaffed" boolean,
    "_dataRegistr" timestamp without time zone NOT NULL,
    "_enterCode" bigint NOT NULL,
    "_goingToTheGame" boolean,
    "EquipmentId" integer,
    "TeamId" integer,
    "StatisticId" integer,
    "EventsForAllCommandsModelEntityId" integer
);


ALTER TABLE public."Players" OWNER TO "HSquadAdmin";

--
-- Name: Players_Id_seq; Type: SEQUENCE; Schema: public; Owner: HSquadAdmin
--

ALTER TABLE public."Players" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Players_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Polygons; Type: TABLE; Schema: public; Owner: HSquadAdmin
--

CREATE TABLE public."Polygons" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Coordinates" text NOT NULL
);


ALTER TABLE public."Polygons" OWNER TO "HSquadAdmin";

--
-- Name: Polygons_Id_seq; Type: SEQUENCE; Schema: public; Owner: HSquadAdmin
--

ALTER TABLE public."Polygons" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Polygons_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Reantils; Type: TABLE; Schema: public; Owner: HSquadAdmin
--

CREATE TABLE public."Reantils" (
    "Id" integer NOT NULL,
    "Weapon" boolean NOT NULL,
    "Mask" boolean NOT NULL,
    "Helmet" boolean NOT NULL,
    "Balaclava" boolean NOT NULL,
    "SVMP" boolean NOT NULL,
    "Outterwear" boolean NOT NULL,
    "Gloves" boolean NOT NULL,
    "BulletproofVestOrUnloadingVest" boolean NOT NULL,
    "IsStaffed" boolean NOT NULL,
    "TeamId" integer NOT NULL
);


ALTER TABLE public."Reantils" OWNER TO "HSquadAdmin";

--
-- Name: Reantils_Id_seq; Type: SEQUENCE; Schema: public; Owner: HSquadAdmin
--

ALTER TABLE public."Reantils" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Reantils_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Teams; Type: TABLE; Schema: public; Owner: HSquadAdmin
--

CREATE TABLE public."Teams" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "CountMembers" integer NOT NULL,
    "EventId" integer
);


ALTER TABLE public."Teams" OWNER TO "HSquadAdmin";

--
-- Name: Teams_Id_seq; Type: SEQUENCE; Schema: public; Owner: HSquadAdmin
--

ALTER TABLE public."Teams" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Teams_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: HSquadAdmin
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO "HSquadAdmin";

--
-- Data for Name: DeviceRegistartionModelEntities; Type: TABLE DATA; Schema: public; Owner: HSquadAdmin
--

COPY public."DeviceRegistartionModelEntities" ("Id", "DeviceToken", "DevicePlatform", "UserId", "CreatedAt", "LastActiveAt", "IsActive", "InstallationId") FROM stdin;
\.


--
-- Data for Name: Equipments; Type: TABLE DATA; Schema: public; Owner: HSquadAdmin
--

COPY public."Equipments" ("Id", "MainWeapon", "NameMainWeapon", "SecondaryWeapon", "NameSecondaryWeapon", "HeadEquipment", "BodyEquipment", "UnloudingEquipment", "OwnerEquipmentId") FROM stdin;
\.


--
-- Data for Name: Events; Type: TABLE DATA; Schema: public; Owner: HSquadAdmin
--

COPY public."Events" ("Id", "NameTeamEnemy", "NamePolygon", "Coordinates", "Date", "Time", "CountMembers", "TeamId") FROM stdin;
\.


--
-- Data for Name: EventsForAllCommands; Type: TABLE DATA; Schema: public; Owner: HSquadAdmin
--

COPY public."EventsForAllCommands" ("Id", "NameGame", "TeamNameOrganization", "TeamIdOrganization", "DescriptionShort", "DescriptionFull", "CoordinatesPolygon", "PolygonName", "DateAndTimeGame") FROM stdin;
\.


--
-- Data for Name: HistoryEvents; Type: TABLE DATA; Schema: public; Owner: HSquadAdmin
--

COPY public."HistoryEvents" ("Id", "NamePolygon", "CoordinatesPolygon", "DateEvent") FROM stdin;
\.


--
-- Data for Name: Notifications; Type: TABLE DATA; Schema: public; Owner: HSquadAdmin
--

COPY public."Notifications" ("Id", "Title", "Message", "Type", "Priority", "RelatedUserId", "DataJson", "CreatedAt", "IsRead", "IsSent", "UserId", "EventId") FROM stdin;
\.


--
-- Data for Name: PlayerStatistics; Type: TABLE DATA; Schema: public; Owner: HSquadAdmin
--

COPY public."PlayerStatistics" ("Id", "NamePlayer", "CallSingPlayer", "CountKill", "CountDieds", "CountFees", "CountEvents", "LastUpdateDataStatistics", "OldDataJson", "DataRegistr", "RoleUser", "AchievementsJson", "IsCommanderCheck", "UserModelId") FROM stdin;
\.


--
-- Data for Name: Players; Type: TABLE DATA; Schema: public; Owner: HSquadAdmin
--

COPY public."Players" ("Id", _role, "_callSing", "_teamName", "_phoneNumber", "_userName", _age, "_isStaffed", "_dataRegistr", "_enterCode", "_goingToTheGame", "EquipmentId", "TeamId", "StatisticId", "EventsForAllCommandsModelEntityId") FROM stdin;
1	2	Bezumie	Dr	897383	Roma	\N	\N	2026-04-11 14:11:41.362234	897383	\N	\N	1	\N	\N
\.


--
-- Data for Name: Polygons; Type: TABLE DATA; Schema: public; Owner: HSquadAdmin
--

COPY public."Polygons" ("Id", "Name", "Coordinates") FROM stdin;
\.


--
-- Data for Name: Reantils; Type: TABLE DATA; Schema: public; Owner: HSquadAdmin
--

COPY public."Reantils" ("Id", "Weapon", "Mask", "Helmet", "Balaclava", "SVMP", "Outterwear", "Gloves", "BulletproofVestOrUnloadingVest", "IsStaffed", "TeamId") FROM stdin;
\.


--
-- Data for Name: Teams; Type: TABLE DATA; Schema: public; Owner: HSquadAdmin
--

COPY public."Teams" ("Id", "Name", "CountMembers", "EventId") FROM stdin;
1	Dr	1	\N
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: HSquadAdmin
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20260410152405_msiMigr	10.0.5
\.


--
-- Name: Equipments_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: HSquadAdmin
--

SELECT pg_catalog.setval('public."Equipments_Id_seq"', 1, false);


--
-- Name: EventsForAllCommands_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: HSquadAdmin
--

SELECT pg_catalog.setval('public."EventsForAllCommands_Id_seq"', 1, false);


--
-- Name: Events_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: HSquadAdmin
--

SELECT pg_catalog.setval('public."Events_Id_seq"', 1, false);


--
-- Name: HistoryEvents_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: HSquadAdmin
--

SELECT pg_catalog.setval('public."HistoryEvents_Id_seq"', 1, false);


--
-- Name: Notifications_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: HSquadAdmin
--

SELECT pg_catalog.setval('public."Notifications_Id_seq"', 1, false);


--
-- Name: PlayerStatistics_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: HSquadAdmin
--

SELECT pg_catalog.setval('public."PlayerStatistics_Id_seq"', 1, false);


--
-- Name: Players_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: HSquadAdmin
--

SELECT pg_catalog.setval('public."Players_Id_seq"', 1, true);


--
-- Name: Polygons_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: HSquadAdmin
--

SELECT pg_catalog.setval('public."Polygons_Id_seq"', 1, false);


--
-- Name: Reantils_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: HSquadAdmin
--

SELECT pg_catalog.setval('public."Reantils_Id_seq"', 1, false);


--
-- Name: Teams_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: HSquadAdmin
--

SELECT pg_catalog.setval('public."Teams_Id_seq"', 1, true);


--
-- Name: DeviceRegistartionModelEntities PK_DeviceRegistartionModelEntities; Type: CONSTRAINT; Schema: public; Owner: HSquadAdmin
--

ALTER TABLE ONLY public."DeviceRegistartionModelEntities"
    ADD CONSTRAINT "PK_DeviceRegistartionModelEntities" PRIMARY KEY ("Id");


--
-- Name: Equipments PK_Equipments; Type: CONSTRAINT; Schema: public; Owner: HSquadAdmin
--

ALTER TABLE ONLY public."Equipments"
    ADD CONSTRAINT "PK_Equipments" PRIMARY KEY ("Id");


--
-- Name: Events PK_Events; Type: CONSTRAINT; Schema: public; Owner: HSquadAdmin
--

ALTER TABLE ONLY public."Events"
    ADD CONSTRAINT "PK_Events" PRIMARY KEY ("Id");


--
-- Name: EventsForAllCommands PK_EventsForAllCommands; Type: CONSTRAINT; Schema: public; Owner: HSquadAdmin
--

ALTER TABLE ONLY public."EventsForAllCommands"
    ADD CONSTRAINT "PK_EventsForAllCommands" PRIMARY KEY ("Id");


--
-- Name: HistoryEvents PK_HistoryEvents; Type: CONSTRAINT; Schema: public; Owner: HSquadAdmin
--

ALTER TABLE ONLY public."HistoryEvents"
    ADD CONSTRAINT "PK_HistoryEvents" PRIMARY KEY ("Id");


--
-- Name: Notifications PK_Notifications; Type: CONSTRAINT; Schema: public; Owner: HSquadAdmin
--

ALTER TABLE ONLY public."Notifications"
    ADD CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id");


--
-- Name: PlayerStatistics PK_PlayerStatistics; Type: CONSTRAINT; Schema: public; Owner: HSquadAdmin
--

ALTER TABLE ONLY public."PlayerStatistics"
    ADD CONSTRAINT "PK_PlayerStatistics" PRIMARY KEY ("Id");


--
-- Name: Players PK_Players; Type: CONSTRAINT; Schema: public; Owner: HSquadAdmin
--

ALTER TABLE ONLY public."Players"
    ADD CONSTRAINT "PK_Players" PRIMARY KEY ("Id");


--
-- Name: Polygons PK_Polygons; Type: CONSTRAINT; Schema: public; Owner: HSquadAdmin
--

ALTER TABLE ONLY public."Polygons"
    ADD CONSTRAINT "PK_Polygons" PRIMARY KEY ("Id");


--
-- Name: Reantils PK_Reantils; Type: CONSTRAINT; Schema: public; Owner: HSquadAdmin
--

ALTER TABLE ONLY public."Reantils"
    ADD CONSTRAINT "PK_Reantils" PRIMARY KEY ("Id");


--
-- Name: Teams PK_Teams; Type: CONSTRAINT; Schema: public; Owner: HSquadAdmin
--

ALTER TABLE ONLY public."Teams"
    ADD CONSTRAINT "PK_Teams" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: HSquadAdmin
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: IX_DeviceRegistartionModelEntities_UserId; Type: INDEX; Schema: public; Owner: HSquadAdmin
--

CREATE INDEX "IX_DeviceRegistartionModelEntities_UserId" ON public."DeviceRegistartionModelEntities" USING btree ("UserId");


--
-- Name: IX_Equipments_OwnerEquipmentId; Type: INDEX; Schema: public; Owner: HSquadAdmin
--

CREATE UNIQUE INDEX "IX_Equipments_OwnerEquipmentId" ON public."Equipments" USING btree ("OwnerEquipmentId");


--
-- Name: IX_Notifications_EventId; Type: INDEX; Schema: public; Owner: HSquadAdmin
--

CREATE INDEX "IX_Notifications_EventId" ON public."Notifications" USING btree ("EventId");


--
-- Name: IX_Notifications_UserId; Type: INDEX; Schema: public; Owner: HSquadAdmin
--

CREATE INDEX "IX_Notifications_UserId" ON public."Notifications" USING btree ("UserId");


--
-- Name: IX_PlayerStatistics_UserModelId; Type: INDEX; Schema: public; Owner: HSquadAdmin
--

CREATE UNIQUE INDEX "IX_PlayerStatistics_UserModelId" ON public."PlayerStatistics" USING btree ("UserModelId");


--
-- Name: IX_Players_EquipmentId; Type: INDEX; Schema: public; Owner: HSquadAdmin
--

CREATE UNIQUE INDEX "IX_Players_EquipmentId" ON public."Players" USING btree ("EquipmentId");


--
-- Name: IX_Players_EventsForAllCommandsModelEntityId; Type: INDEX; Schema: public; Owner: HSquadAdmin
--

CREATE INDEX "IX_Players_EventsForAllCommandsModelEntityId" ON public."Players" USING btree ("EventsForAllCommandsModelEntityId");


--
-- Name: IX_Players_TeamId; Type: INDEX; Schema: public; Owner: HSquadAdmin
--

CREATE INDEX "IX_Players_TeamId" ON public."Players" USING btree ("TeamId");


--
-- Name: IX_Reantils_TeamId; Type: INDEX; Schema: public; Owner: HSquadAdmin
--

CREATE INDEX "IX_Reantils_TeamId" ON public."Reantils" USING btree ("TeamId");


--
-- Name: IX_Teams_EventId; Type: INDEX; Schema: public; Owner: HSquadAdmin
--

CREATE UNIQUE INDEX "IX_Teams_EventId" ON public."Teams" USING btree ("EventId");


--
-- Name: DeviceRegistartionModelEntities FK_DeviceRegistartionModelEntities_Players_UserId; Type: FK CONSTRAINT; Schema: public; Owner: HSquadAdmin
--

ALTER TABLE ONLY public."DeviceRegistartionModelEntities"
    ADD CONSTRAINT "FK_DeviceRegistartionModelEntities_Players_UserId" FOREIGN KEY ("UserId") REFERENCES public."Players"("Id");


--
-- Name: Notifications FK_Notifications_Events_EventId; Type: FK CONSTRAINT; Schema: public; Owner: HSquadAdmin
--

ALTER TABLE ONLY public."Notifications"
    ADD CONSTRAINT "FK_Notifications_Events_EventId" FOREIGN KEY ("EventId") REFERENCES public."Events"("Id");


--
-- Name: Notifications FK_Notifications_Players_UserId; Type: FK CONSTRAINT; Schema: public; Owner: HSquadAdmin
--

ALTER TABLE ONLY public."Notifications"
    ADD CONSTRAINT "FK_Notifications_Players_UserId" FOREIGN KEY ("UserId") REFERENCES public."Players"("Id");


--
-- Name: PlayerStatistics FK_PlayerStatistics_Players_UserModelId; Type: FK CONSTRAINT; Schema: public; Owner: HSquadAdmin
--

ALTER TABLE ONLY public."PlayerStatistics"
    ADD CONSTRAINT "FK_PlayerStatistics_Players_UserModelId" FOREIGN KEY ("UserModelId") REFERENCES public."Players"("Id") ON DELETE CASCADE;


--
-- Name: Players FK_Players_Equipments_EquipmentId; Type: FK CONSTRAINT; Schema: public; Owner: HSquadAdmin
--

ALTER TABLE ONLY public."Players"
    ADD CONSTRAINT "FK_Players_Equipments_EquipmentId" FOREIGN KEY ("EquipmentId") REFERENCES public."Equipments"("Id") ON DELETE CASCADE;


--
-- Name: Players FK_Players_EventsForAllCommands_EventsForAllCommandsModelEntit~; Type: FK CONSTRAINT; Schema: public; Owner: HSquadAdmin
--

ALTER TABLE ONLY public."Players"
    ADD CONSTRAINT "FK_Players_EventsForAllCommands_EventsForAllCommandsModelEntit~" FOREIGN KEY ("EventsForAllCommandsModelEntityId") REFERENCES public."EventsForAllCommands"("Id");


--
-- Name: Players FK_Players_Teams_TeamId; Type: FK CONSTRAINT; Schema: public; Owner: HSquadAdmin
--

ALTER TABLE ONLY public."Players"
    ADD CONSTRAINT "FK_Players_Teams_TeamId" FOREIGN KEY ("TeamId") REFERENCES public."Teams"("Id") ON DELETE SET NULL;


--
-- Name: Reantils FK_Reantils_Teams_TeamId; Type: FK CONSTRAINT; Schema: public; Owner: HSquadAdmin
--

ALTER TABLE ONLY public."Reantils"
    ADD CONSTRAINT "FK_Reantils_Teams_TeamId" FOREIGN KEY ("TeamId") REFERENCES public."Teams"("Id") ON DELETE CASCADE;


--
-- Name: Teams FK_Teams_Events_EventId; Type: FK CONSTRAINT; Schema: public; Owner: HSquadAdmin
--

ALTER TABLE ONLY public."Teams"
    ADD CONSTRAINT "FK_Teams_Events_EventId" FOREIGN KEY ("EventId") REFERENCES public."Events"("Id") ON DELETE SET NULL;


--
-- PostgreSQL database dump complete
--

\unrestrict OTJ4eKZoN1j7yLI9hcuxWqTCnCvNaFsBtDJphLhfXR9e9X0Zi6j3p01rDHBf5nT

