// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SquadServer.Models.DbContextDir;

#nullable disable

namespace SquadServer.Migrations
{
    [DbContext(typeof(SquadDbContext))]
    [Migration("20251204134528_One")]
    partial class One
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SquadServer.Models.EquipmentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("BodyEquipment")
                        .HasColumnType("bit");

                    b.Property<bool>("HeadEquipment")
                        .HasColumnType("bit");

                    b.Property<bool>("MainWeapon")
                        .HasColumnType("bit");

                    b.Property<string>("NameMainWeapon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NameSecondaryWeapon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerEquipmentId")
                        .HasColumnType("int");

                    b.Property<bool>("SecondaryWeapon")
                        .HasColumnType("bit");

                    b.Property<bool>("UnloudingEquipment")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("OwnerEquipmentId")
                        .IsUnique();

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("SquadServer.Models.ModelsEntity.EventModelEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Coordinates")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountMembers")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("NamePolygon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameTeamEnemy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("SquadServer.Models.ModelsEntity.HisoryEventsModelEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CoordinatesPolygon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DateEvent")
                        .HasColumnType("date");

                    b.Property<string>("NamePolygon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HistoryEvents");
                });

            modelBuilder.Entity("SquadServer.Models.PolygonEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Coordinates")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Polygons");
                });

            modelBuilder.Entity("SquadServer.Models.ReantalEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Balaclava")
                        .HasColumnType("bit");

                    b.Property<bool>("BulletproofVestOrUnloadingVest")
                        .HasColumnType("bit");

                    b.Property<bool>("Gloves")
                        .HasColumnType("bit");

                    b.Property<bool>("Helmet")
                        .HasColumnType("bit");

                    b.Property<bool>("Mask")
                        .HasColumnType("bit");

                    b.Property<bool>("Outterwear")
                        .HasColumnType("bit");

                    b.Property<bool>("SVMP")
                        .HasColumnType("bit");

                    b.Property<bool>("Weapon")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Reantils");
                });

            modelBuilder.Entity("SquadServer.Models.UserModelEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<int?>("_age")
                        .HasColumnType("int");

                    b.Property<string>("_callSing")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("_goingToTheGame")
                        .HasColumnType("bit");

                    b.Property<bool?>("_isStaffed")
                        .HasColumnType("bit");

                    b.Property<string>("_phoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("_role")
                        .HasColumnType("tinyint");

                    b.Property<string>("_teamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_userName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("SquadServer.Models.EquipmentEntity", b =>
                {
                    b.HasOne("SquadServer.Models.UserModelEntity", "OwnerEquipment")
                        .WithOne("Equipment")
                        .HasForeignKey("SquadServer.Models.EquipmentEntity", "OwnerEquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnerEquipment");
                });

            modelBuilder.Entity("SquadServer.Models.UserModelEntity", b =>
                {
                    b.Navigation("Equipment");
                });
#pragma warning restore 612, 618
        }
    }
}
