// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SquadServer.Models.DbContextDir;

#nullable disable

namespace SquadServer.Migrations
{
    [DbContext(typeof(SquadDbContext))]
    partial class SquadDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SquadServer.Models.EquipmentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("BodyEquipment")
                        .HasColumnType("bit");

                    b.Property<bool>("HeadEquipment")
                        .HasColumnType("bit");

                    b.Property<bool>("MainWeapon")
                        .HasColumnType("bit");

                    b.Property<string>("NameMainWeapon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NameSecondaryWeapon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerEquipmentId")
                        .HasColumnType("int");

                    b.Property<bool>("SecondaryWeapon")
                        .HasColumnType("bit");

                    b.Property<bool>("UnloudingEquipment")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("OwnerEquipmentId")
                        .IsUnique();

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("SquadServer.Models.ModelsEntity.DeviceRegistartionModelEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DevicePlatform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("InstallationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastActiveAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DeviceRegistartionModelEntities");
                });

            modelBuilder.Entity("SquadServer.Models.ModelsEntity.EventModelEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Coordinates")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountMembers")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("NamePolygon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameTeamEnemy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("SquadServer.Models.ModelsEntity.EventsForAllCommandsModelEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CoordinatesPolygon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionFull")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionShort")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PolygonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamIdOrganization")
                        .HasColumnType("int");

                    b.Property<string>("TeamNameOrganization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EventsForAllCommands");
                });

            modelBuilder.Entity("SquadServer.Models.ModelsEntity.HisoryEventsModelEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CoordinatesPolygon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DateEvent")
                        .HasColumnType("date");

                    b.Property<string>("NamePolygon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HistoryEvents");
                });

            modelBuilder.Entity("SquadServer.Models.ModelsEntity.NotificationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EventId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSent")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int?>("RelatedUserId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("SquadServer.Models.ModelsEntity.PlayerStatisticsModelEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AchievementsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CallSingPlayer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountDieds")
                        .HasColumnType("int");

                    b.Property<int>("CountEvents")
                        .HasColumnType("int");

                    b.Property<int>("CountFees")
                        .HasColumnType("int");

                    b.Property<int>("CountKill")
                        .HasColumnType("int");

                    b.Property<bool>("IsCommanderCheck")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateDataStatistics")
                        .HasColumnType("datetime2");

                    b.Property<string>("NamePlayer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldDataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PlayerStatistics");
                });

            modelBuilder.Entity("SquadServer.Models.ModelsEntity.TeamEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountMembers")
                        .HasColumnType("int");

                    b.Property<int?>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasFilter("[EventId] IS NOT NULL");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("SquadServer.Models.PolygonEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Coordinates")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Polygons");
                });

            modelBuilder.Entity("SquadServer.Models.ReantalEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Balaclava")
                        .HasColumnType("bit");

                    b.Property<bool>("BulletproofVestOrUnloadingVest")
                        .HasColumnType("bit");

                    b.Property<bool>("Gloves")
                        .HasColumnType("bit");

                    b.Property<bool>("Helmet")
                        .HasColumnType("bit");

                    b.Property<bool>("Mask")
                        .HasColumnType("bit");

                    b.Property<bool>("Outterwear")
                        .HasColumnType("bit");

                    b.Property<bool>("SVMP")
                        .HasColumnType("bit");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<bool>("Weapon")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Reantils");
                });

            modelBuilder.Entity("SquadServer.Models.UserModelEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<int?>("EventsForAllCommandsModelEntityId")
                        .HasColumnType("int");

                    b.Property<int?>("StatisticId")
                        .HasColumnType("int");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.Property<int?>("_age")
                        .HasColumnType("int");

                    b.Property<string>("_callSing")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("_enterCode")
                        .HasColumnType("bigint");

                    b.Property<bool?>("_goingToTheGame")
                        .HasColumnType("bit");

                    b.Property<bool?>("_isStaffed")
                        .HasColumnType("bit");

                    b.Property<string>("_phoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("_role")
                        .HasColumnType("tinyint");

                    b.Property<string>("_teamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_userName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EventsForAllCommandsModelEntityId");

                    b.HasIndex("StatisticId")
                        .IsUnique()
                        .HasFilter("[StatisticId] IS NOT NULL");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("SquadServer.Models.EquipmentEntity", b =>
                {
                    b.HasOne("SquadServer.Models.UserModelEntity", "OwnerEquipment")
                        .WithOne("Equipment")
                        .HasForeignKey("SquadServer.Models.EquipmentEntity", "OwnerEquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnerEquipment");
                });

            modelBuilder.Entity("SquadServer.Models.ModelsEntity.DeviceRegistartionModelEntity", b =>
                {
                    b.HasOne("SquadServer.Models.UserModelEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SquadServer.Models.ModelsEntity.NotificationEntity", b =>
                {
                    b.HasOne("SquadServer.Models.ModelsEntity.EventModelEntity", "Event")
                        .WithMany()
                        .HasForeignKey("EventId");

                    b.HasOne("SquadServer.Models.UserModelEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SquadServer.Models.ModelsEntity.TeamEntity", b =>
                {
                    b.HasOne("SquadServer.Models.ModelsEntity.EventModelEntity", "Event")
                        .WithOne("Team")
                        .HasForeignKey("SquadServer.Models.ModelsEntity.TeamEntity", "EventId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Event");
                });

            modelBuilder.Entity("SquadServer.Models.ReantalEntity", b =>
                {
                    b.HasOne("SquadServer.Models.ModelsEntity.TeamEntity", "TeamEntity")
                        .WithMany("Reantals")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeamEntity");
                });

            modelBuilder.Entity("SquadServer.Models.UserModelEntity", b =>
                {
                    b.HasOne("SquadServer.Models.ModelsEntity.EventsForAllCommandsModelEntity", null)
                        .WithMany("Players")
                        .HasForeignKey("EventsForAllCommandsModelEntityId");

                    b.HasOne("SquadServer.Models.ModelsEntity.PlayerStatisticsModelEntity", "Statistic")
                        .WithOne("UserModel")
                        .HasForeignKey("SquadServer.Models.UserModelEntity", "StatisticId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SquadServer.Models.ModelsEntity.TeamEntity", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Statistic");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SquadServer.Models.ModelsEntity.EventModelEntity", b =>
                {
                    b.Navigation("Team")
                        .IsRequired();
                });

            modelBuilder.Entity("SquadServer.Models.ModelsEntity.EventsForAllCommandsModelEntity", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("SquadServer.Models.ModelsEntity.PlayerStatisticsModelEntity", b =>
                {
                    b.Navigation("UserModel")
                        .IsRequired();
                });

            modelBuilder.Entity("SquadServer.Models.ModelsEntity.TeamEntity", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Reantals");
                });

            modelBuilder.Entity("SquadServer.Models.UserModelEntity", b =>
                {
                    b.Navigation("Equipment");
                });
#pragma warning restore 612, 618
        }
    }
}
