
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY SquadServer/SquadServer.csproj SquadServer/
RUN dotnet restore SquadServer/SquadServer.csproj
COPY . .
RUN dotnet publish SquadServer/SquadServer.csproj -c Release -o /app



FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "SquadServer.dll"]