global using Microsoft.EntityFrameworkCore;
global using SquadServer.Models.DbContextDir;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using SquadServer.Models.ModelsConfig;
global using SquadServer.Models.ModelsEntity;
global using SquadServer.DTO_Classes;
global using SquadServer.DTO_Classes.DTO_AuxiliaryModels;
global using SquadServer.Extension;
global using SquadServer.Models;
global using SquadServer.Repositoryes;
global using System.Text.Json;
namespace SquadServer;
