global using Microsoft.EntityFrameworkCore;
global using SquadServer.Models.DbContextDir;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using SquadServer.Models.ModelsConfig;
global using SquadServer.Models.ModelsEntity;
global using SquadServer.DTO_Classes;
global using SquadServer.DTO_Classes.DTO_AuxiliaryModels;
global using SquadServer.Extension;
global using SquadServer.Models;
global using SquadServer.Repositoryes;
global using System.Text.Json;
global using SquadServer.DTO_Classes.DTO_DeviceModel;
global using SquadServer.Services.Service_DeviceRegistration;
global using SquadServer.Services.Service_Notification;
global using SquadServer.Models.ModelsEntity.AuxiliaryModels;
global using System.Text.Json.Serialization;
global using System.ComponentModel.DataAnnotations.Schema;
global using Microsoft.EntityFrameworkCore.Metadata.Internal;
global using static SquadServer.Controllers.NotificationController;
global using SquadServer.DTO_Classes.DTO_Notifiation;
namespace SquadServer;
